# netlify.toml – Build-Konfiguration für Hugo + Theme-Submodule

[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  NODE_VERSION = "22"

# Optional: Redirects (falls du mal /index.html -> / haben willst)
# [[redirects]]
#   from = "/index.html"
#   to = "/"
#   status = 301
